package ftdi;
import com.sun.jna.Structure;
import ftdi.FtdiLibrary.libusb_device;
import java.util.Arrays;
import java.util.List;
/**
 * \brief list of usb devices created by ftdi_usb_find_all()<br>
 * <i>native declaration : /usr/include/sys/time.h:486</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ftdi_device_list extends Structure {
	/**
	 * pointer to next entry<br>
	 * C type : ftdi_device_list*
	 */
	public ftdi_device_list.ByReference next;
	/**
	 * pointer to libusb's usb_device<br>
	 * C type : libusb_device*
	 */
	public libusb_device dev;
	public ftdi_device_list() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("next", "dev");
	}
	/**
	 * @param next pointer to next entry<br>
	 * C type : ftdi_device_list*<br>
	 * @param dev pointer to libusb's usb_device<br>
	 * C type : libusb_device*
	 */
	public ftdi_device_list(ftdi_device_list.ByReference next, libusb_device dev) {
		super();
		this.next = next;
		this.dev = dev;
	}
	public static class ByReference extends ftdi_device_list implements Structure.ByReference {
		
	};
	public static class ByValue extends ftdi_device_list implements Structure.ByValue {
		
	};
}
